configure: revert glib dependency to 2.34
This reverts the glib part of commit 4c3991. That commit increased the
compile time dependency to glib 2.38 while still only checking for
2.34 at compile time, leading to compile errors in GNOME 3.8 as built
by jhbuild:

/work/gnome/install/include/glib-2.0/glib/gversionmacros.h:140:7: warning: "GLIB_VERSION_2_38" is not defined [-Wundef]
/work/gnome/install/include/glib-2.0/glib/gversionmacros.h:176:2: error: #error "GLIB_VERSION_MAX_ALLOWED must be >= GLIB_VERSION_MIN_REQUIRED"

It is uncertain whether the new glib is really needed. The commit
message only mentioned GTK+, not glib:

  commit 4c39917dbf3c82fa6fa816d655d5889f4e17c8c0
  Author: Tristan Van Berkom <tristan.van.berkom@gmail.com>
  Date:   Mon Aug 19 20:21:06 2013 +0200

    Bump required GTK+ version to 3.10

    The GTK+ requirement is a soft dependancy, bumping it for the
    purpose of building the cursor example program which uses the
    new template features from GTK+