tests: Avoid complaints about vanished peers
Tests failed when the DBus session ended early because of this warning from
GDBus/ETestDBus: "g_dbus_connection_real_closed: Remote peer vanished with
error: Underlying GIOStream returned 0 bytes on an async read
(g-io-error-quark, 0). Exiting."