build: dolt has some link issues with library dependency
This might not be seen when linking with a previously installed system
library. But in a jail, like with jhbuild, it fails to link, in a
clean build environment.

The workaround is to explicitely link with the missing library.

http://bugzilla.gnome.org/show_bug.cgi?id=582110

make[3]: Entering directory `/opt/git/evolution-data-server/src'
../doltlibtool --tag=CC   --mode=link gcc-4.3  -g -O0 -Wall -Wmissing-prototypes  -Wno-sign-compare -Wno-pointer-sign  -L/opt/gnome2/lib  -o evolution-data-server  Evolution-DataServer-common.o Evolution-DataServer-skels.o Evolution-DataServer-stubs.o server-interface-check.o server-logging.o server.o offline-listener.o ../libebackend/libebackend-1.2.la ../addressbook/libedata-book/libedata-book-1.2.la ../calendar/libedata-cal/libedata-cal-1.2.la -pthread -L/opt/gnome2/lib -lgnome-2 -lpopt -lbonobo-2 -lbonobo-activation -lgmodule-2.0 -lORBit-2 -lgthread-2.0 -lrt -lgobject-2.0 -lglib-2.0 -lplds4 -lplc4 -lnspr4 -lpthread -ldl -lical -licalss -licalvcal   -lpthread    -pthread -L/opt/gnome2/lib -lxml2 -lbonobo-2 -lbonobo-activation -lORBit-2 -lgthread-2.0 -lrt -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lgmodule-2.0 -lgconf-2 -lglib-2.0 -lplds4 -lplc4 -lnspr4 -lpthread -ldl   -lpthread
libtool: link: gcc-4.3 -g -O0 -Wall -Wmissing-prototypes -Wno-sign-compare -Wno-pointer-sign -o .libs/evolution-data-server Evolution-DataServer-common.o Evolution-DataServer-skels.o Evolution-DataServer-stubs.o server-interface-check.o server-logging.o server.o offline-listener.o -pthread -pthread  -L/opt/gnome2/lib ../libebackend/.libs/libebackend-1.2.so ../addressbook/libedata-book/.libs/libedata-book-1.2.so ../calendar/libedata-cal/.libs/libedata-cal-1.2.so /opt/gnome2/lib/libgnome-2.so /usr/lib/libpopt.so /opt/gnome2/lib/libical.so /opt/gnome2/lib/libicalss.so /opt/gnome2/lib/libicalvcal.so /opt/gnome2/lib/libxml2.so /opt/gnome2/lib/libbonobo-2.so /opt/gnome2/lib/libbonobo-activation.so /opt/gnome2/lib/libORBit-2.so /opt/gnome2/lib/libgthread-2.0.so -lrt /opt/gnome2/lib/libsoup-2.4.so /opt/gnome2/lib/libgio-2.0.so /opt/gnome2/lib/libgobject-2.0.so /opt/gnome2/lib/libgmodule-2.0.so /opt/gnome2/lib/libgconf-2.so /opt/gnome2/lib/libglib-2.0.so -lplds4 -lplc4 -lnspr4 -ldl -lpthread -pthread -Wl,-rpath -Wl,/opt/gnome2/lib
../addressbook/libedata-book/.libs/libedata-book-1.2.so: undefined reference to `e_util_utf8_remove_accents'