data_book_error_from_gdata_error: Make sure we actually set an error.
Had an instance where the error code didn't match one of the predefined
cases.  The GError never got set, and we crashed trying to deference it.